[window]
opacity = 0.95

[window.padding]
x = 8
y = 8

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font" 
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[scrolling]
history = 1000
multiplier = 3

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"
